project:
  type: website
  output-dir: docs
  resources:
    - files/*

book:
  title: "Portela's page"
  author: "Miguel Portela"
  date: "15/10/2024"
  search: true
  chapters:
    - index.qmd
    - papers.qmd

format:
  html:
    theme: cosmo
